### PR TITLE
Updated features.js so that logos aligned to text

### PR DESCRIPTION
**Pull request by AashishBathe**
The images are now aligned to the text in the features.js file. Issue #26 is resolved. Please comment if any changes necessary.

### CODE REVIEW

**Comment by DarrenDsouza7273** [comment]
Good work @AashishBathe , While working on this task, kindly ensure that the alignment of the headings (Connect, Learn, Grow) and their respective descriptions is consistent and uniform.

**Comment by AashishBathe** [comment]
It's all good 👍

**Review by Savio629 — APPROVED** [review]

**Review by Savio629 — COMMENTED** [review]
@AashishBathe Is there any other way to align the images instead of using marginLeft with so much of px?

**Comment by AashishBathe** [comment]
@Savio629 Hey, I found an alternate way using display and margin, in order to always center, rather than fixed size.

**Review by Savio629 — APPROVED** [review]
Looks better

**Comment by Savio629** [comment]
Thank you for your contribution 👍

**Pull request merged**
