### PR TITLE
Fix: Make navbar mobile responsive #17

### PR DESCRIPTION
**Pull request by Rahul-Roy-Hub**
Fix:
The nav elements will appear only on clicking on the hamburger icon

Navbar

Make Navbar appears whole screen when clicked
Navbar

### CODE REVIEW

**Comment by Savio629** [comment]
@Rahul-Roy-Hub You weren't assigned the issue!
Now as you are working on it, instead of the nav elements showing in a small tab, update it to cover the whole screen

**Comment by Rahul-Roy-Hub** [comment]
@Savio629 Yeah I will do that but  @akash0708 working on it as said, plz accept that PR for small contribution towards it. If further issues found i will definitely work on it.

**Comment by akash0708** [comment]
@Rahul-Roy-Hub I was about to create a custom navbar, but I suppose you are making changes within the mui component. You can go forward with the issue. @Savio629 you can unassign me.

**Comment by Rahul-Roy-Hub** [comment]
@Savio629

**Comment by Savio629** [comment]
@Rahul-Roy-Hub Try to add a animation when the hamburger menu is clicked and decrease margin for nav elements.

**Comment by Savio629** [comment]
Resolve the conflicts and implement the above changes @Rahul-Roy-Hub

**Pull request closed without merging**
